token.o:
	$(CXX) -c token.cxx -o token.o

base.o:
	$(CXX) -c base.cxx -o base.o

number.o:
	$(CXX) -c number.cxx -o number.o

identifier.o:
	$(CXX) -c identifier.cxx -o identifier.o

operator.o:
	$(CXX) -c operator.cxx -o operator.o

clean:
	rm -rf *.o
